#version 450

layout (local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

layout (set = 0, binding = 0) restrict writeonly uniform image2D hiz;
layout (set = 0, binding = 1) uniform sampler2D depth;

void main() {
    ivec2 img_coord = ivec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y);
    ivec2 img_size = imageSize(hiz);
    vec2 uv = (img_coord + 0.5) / img_size;

    imageStore(hiz, img_coord, texture(depth, uv));
}

